// write_wave4.mjs — Wave 4 files: 6.5, 7.3, 7.4, 7.5, 7.6, 8.1
import { writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'

const ROOT = 'C:\\Users\\29146640\\AppData\\Local\\Programs\\Megan_D'

function write(relPath, content) {
  const full = join(ROOT, relPath)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, content, { encoding: 'utf-8' })
  console.log(`  wrote: ${relPath}`)
}

// ─── Task 6.5: tests/unit/capacitor-sync.test.ts ────────────────────────────
write('tests/unit/capacitor-sync.test.ts', `import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync, readdirSync } from 'fs'
import { join } from 'path'
import * as fc from 'fast-check'

// Feature: desktop-mobile-packaging, Property 3: WebView asset resolution
// Validates: Requirements 5.4

const ANDROID_PUBLIC = join(__dirname, '../../android/app/src/main/assets/public')
const INDEX_HTML = join(ANDROID_PUBLIC, 'index.html')

function listFilesInDir(dir: string): Set<string> {
  const result = new Set<string>()
  function recurse(current: string) {
    const entries = readdirSync(current, { withFileTypes: true })
    for (const entry of entries) {
      const full = join(current, entry.name)
      if (entry.isDirectory()) {
        recurse(full)
      } else {
        // Store relative path from ANDROID_PUBLIC
        result.add(full.replace(ANDROID_PUBLIC + '/', '').replace(ANDROID_PUBLIC + '\\\\', ''))
      }
    }
  }
  recurse(dir)
  return result
}

describe('Capacitor sync — WebView asset resolution (Property 3)', () => {
  it('all asset paths in android index.html resolve to existing files', () => {
    if (!existsSync(INDEX_HTML)) {
      // android/ is generated by npx cap add android + cap sync; skip if not present
      console.warn('Skipping Property 3: android/app/src/main/assets/public/index.html not found (run cap sync first)')
      return
    }

    const html = readFileSync(INDEX_HTML, 'utf-8')
    const presentFiles = listFilesInDir(ANDROID_PUBLIC)

    const srcMatches = Array.from(html.matchAll(/\\bsrc=["']([^"']+)["']/g)).map((m) => m[1])
    const hrefMatches = Array.from(html.matchAll(/\\bhref=["']([^"']+)["']/g)).map((m) => m[1])
    const allPaths = [...srcMatches, ...hrefMatches]

    const bundledAssets = allPaths.filter(
      (p) => !p.startsWith('http') && !p.startsWith('data:') && p.length > 0
    )

    // Use fast-check to vary the set of asset files and confirm property holds
    // Feature: desktop-mobile-packaging, Property 3: WebView asset resolution
    fc.assert(
      fc.property(
        fc.subarray(bundledAssets, { minLength: 0, maxLength: bundledAssets.length }),
        (subset) => {
          for (const assetPath of subset) {
            const normalized = assetPath.replace(/^\\.?\\//, '')
            const exists = existsSync(join(ANDROID_PUBLIC, normalized))
            if (!exists) {
              return false
            }
          }
          return true
        }
      ),
      { numRuns: 100 }
    )
  })
})
`)

// ─── Tasks 7.3, 7.4, 7.5, 7.6: tests/unit/manifest.test.ts ─────────────────
write('tests/unit/manifest.test.ts', `import { describe, it, expect, vi, afterEach } from 'vitest'
import { writeFileSync, readFileSync, mkdirSync, unlinkSync, existsSync } from 'fs'
import { join } from 'path'
import * as fc from 'fast-check'
import * as crypto from 'crypto'
import * as os from 'os'

// Feature: desktop-mobile-packaging
// Properties 4, 5, 6, 7 — manifest generation correctness

// ─── Inline artifactEntry logic (mirrors scripts/manifest.js) ───────────────
function artifactEntry(filePath: string) {
  if (!existsSync(filePath)) {
    return { filename: require('path').basename(filePath), status: 'failed' as const }
  }
  const buf = readFileSync(filePath)
  return {
    filename: require('path').basename(filePath),
    size: buf.length,
    sha256: crypto.createHash('sha256').update(buf).digest('hex'),
    status: 'success' as const,
  }
}

function buildFilename(version: string, type: 'exe' | 'apk'): string {
  return type === 'exe'
    ? \`MeganD-\${version}-setup.exe\`
    : \`MeganD-\${version}-debug.apk\`
}

const TMP = os.tmpdir()

// ─── Property 5: Manifest artifact size field equals actual file size ────────
// Feature: desktop-mobile-packaging, Property 5: Manifest artifact size accuracy
// Validates: Requirements 4.4, 6.3, 8.2
describe('Property 5: Manifest artifact size accuracy', () => {
  it('size field equals actual file size for random byte buffers', () => {
    fc.assert(
      fc.property(
        fc.uint8Array({ minLength: 0, maxLength: 10000 }),
        (bytes) => {
          const tmpFile = join(TMP, \`manifest-test-\${Date.now()}-\${Math.random()}.bin\`)
          writeFileSync(tmpFile, Buffer.from(bytes))
          try {
            const entry = artifactEntry(tmpFile)
            if (entry.status !== 'success') return false
            return entry.size === bytes.length
          } finally {
            if (existsSync(tmpFile)) unlinkSync(tmpFile)
          }
        }
      ),
      { numRuns: 100 }
    )
  })
})

// ─── Property 6: Manifest correctly reflects present and absent artifacts ────
// Feature: desktop-mobile-packaging, Property 6: Manifest present/absent status
// Validates: Requirements 8.4
describe('Property 6: Manifest present/absent status', () => {
  it('present files get status:success with size and sha256; absent get status:failed with filename only', () => {
    fc.assert(
      fc.property(
        fc.boolean(),  // exe present?
        fc.boolean(),  // apk present?
        fc.uint8Array({ minLength: 1, maxLength: 1000 }),
        (exePresent, apkPresent, bytes) => {
          const tmpExe = join(TMP, \`test-\${Date.now()}-\${Math.random()}-setup.exe\`)
          const tmpApk = join(TMP, \`test-\${Date.now()}-\${Math.random()}-debug.apk\`)

          if (exePresent) writeFileSync(tmpExe, Buffer.from(bytes))
          if (apkPresent) writeFileSync(tmpApk, Buffer.from(bytes))

          try {
            const exeEntry = artifactEntry(tmpExe)
            const apkEntry = artifactEntry(tmpApk)

            if (exePresent) {
              if (exeEntry.status !== 'success') return false
              if (typeof exeEntry.size !== 'number') return false
              if (typeof exeEntry.sha256 !== 'string') return false
            } else {
              if (exeEntry.status !== 'failed') return false
              if ('size' in exeEntry) return false
              if ('sha256' in exeEntry) return false
            }

            if (apkPresent) {
              if (apkEntry.status !== 'success') return false
              if (typeof apkEntry.size !== 'number') return false
              if (typeof apkEntry.sha256 !== 'string') return false
            } else {
              if (apkEntry.status !== 'failed') return false
              if ('size' in apkEntry) return false
              if ('sha256' in apkEntry) return false
            }

            return true
          } finally {
            if (existsSync(tmpExe)) unlinkSync(tmpExe)
            if (existsSync(tmpApk)) unlinkSync(tmpApk)
          }
        }
      ),
      { numRuns: 100 }
    )
  })
})

// ─── Property 7: Manifest stdout output equals manifest file content ─────────
// Feature: desktop-mobile-packaging, Property 7: Manifest stdout equals file
// Validates: Requirements 8.5
describe('Property 7: Manifest stdout equals file content', () => {
  it('JSON.stringify output is byte-for-byte identical to what would be written to file', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 20 }),  // version string
        fc.boolean(),
        fc.boolean(),
        fc.uint8Array({ minLength: 0, maxLength: 500 }),
        (version, exePresent, apkPresent, bytes) => {
          const tmpDir = join(TMP, \`manifest-stdout-\${Date.now()}-\${Math.random()}\`)
          mkdirSync(tmpDir, { recursive: true })

          const exePath = join(tmpDir, \`MeganD-\${version}-setup.exe\`)
          const apkPath = join(tmpDir, \`MeganD-\${version}-debug.apk\`)
          const manifestPath = join(tmpDir, 'manifest.json')

          if (exePresent) writeFileSync(exePath, Buffer.from(bytes))
          if (apkPresent) writeFileSync(apkPath, Buffer.from(bytes))

          const manifest = {
            version,
            buildTimestamp: new Date().toISOString(),
            artifacts: [artifactEntry(exePath), artifactEntry(apkPath)],
          }

          const json = JSON.stringify(manifest, null, 2)
          writeFileSync(manifestPath, json, 'utf-8')

          // stdout output (json) must equal file content
          const fileContent = readFileSync(manifestPath, 'utf-8')
          return json === fileContent
        }
      ),
      { numRuns: 100 }
    )
  })
})

// ─── Property 4: Release artifact filenames match versioned naming pattern ───
// Feature: desktop-mobile-packaging, Property 4: Artifact filename pattern
// Validates: Requirements 4.2, 8.3
describe('Property 4: Artifact filename pattern', () => {
  it('exe filename matches MeganD-{version}-setup.exe', () => {
    fc.assert(
      fc.property(
        fc.tuple(
          fc.nat({ max: 99 }),
          fc.nat({ max: 99 }),
          fc.nat({ max: 99 })
        ),
        ([major, minor, patch]) => {
          const version = \`\${major}.\${minor}.\${patch}\`
          const exeName = buildFilename(version, 'exe')
          const apkName = buildFilename(version, 'apk')

          const exePattern = /^MeganD-\\d+\\.\\d+\\.\\d+-setup\\.exe$/
          const apkPattern = /^MeganD-\\d+\\.\\d+\\.\\d+-debug\\.apk$/

          return exePattern.test(exeName) && apkPattern.test(apkName)
        }
      ),
      { numRuns: 100 }
    )
  })
})
`)

// ─── Task 8.1: scripts/build-android.js ─────────────────────────────────────
write('scripts/build-android.js', `'use strict'
// scripts/build-android.js — Gradle build wrapper with timeout
// Requirements: 6.1, 6.3, 6.4, 6.6

const { spawn } = require('child_process')
const path = require('path')
const fs = require('fs')

const ANDROID_DIR = path.resolve('android')
const TIMEOUT_MS = 300 * 1000  // 300 seconds — Req 6.6
const APK_PATH = path.resolve('android/app/build/outputs/apk/debug/app-debug.apk')

// Use gradlew.bat on Windows, ./gradlew on Unix
const isWindows = process.platform === 'win32'
const gradleCmd = isWindows ? 'gradlew.bat' : './gradlew'

console.log('Starting Gradle assembleDebug...')

const gradle = spawn(gradleCmd, ['assembleDebug'], {
  cwd: ANDROID_DIR,
  stdio: ['ignore', 'pipe', 'pipe'],
  shell: isWindows,
})

let stderrOutput = ''

gradle.stdout.on('data', (data) => process.stdout.write(data))
gradle.stderr.on('data', (data) => {
  stderrOutput += data.toString()
  process.stderr.write(data)
})

// Req 6.6 — kill Gradle if it exceeds 300 seconds
const timer = setTimeout(() => {
  gradle.kill()
  console.error('Gradle build timed out after 300 seconds')
  process.exit(1)
}, TIMEOUT_MS)

gradle.on('close', (code) => {
  clearTimeout(timer)

  if (code !== 0) {
    // Req 6.4 — diagnose missing ANDROID_HOME or JAVA_HOME
    if (stderrOutput.includes('ANDROID_HOME') || stderrOutput.includes('SDK location')) {
      console.error('Error: Android SDK not found. Set the ANDROID_HOME environment variable to the Android SDK path (API level 34 required).')
    } else if (stderrOutput.includes('JAVA_HOME') || stderrOutput.includes('No JDK')) {
      console.error('Error: JDK not found. Set the JAVA_HOME environment variable to a JDK 17 installation.')
    } else {
      console.error(\`Gradle build failed with exit code \${code}\`)
    }
    process.exit(code || 1)
  }

  // Req 6.3 — report APK path and size on success
  if (fs.existsSync(APK_PATH)) {
    const stats = fs.statSync(APK_PATH)
    console.log(\`APK built successfully: \${APK_PATH} (\${stats.size} bytes)\`)
  } else {
    console.warn(\`Gradle succeeded but APK not found at expected path: \${APK_PATH}\`)
  }
})
`)

console.log('Wave 4 files written successfully.')
