export function exportToJSON(data: any, filename: string): void {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportToCSV(data: any[], filename: string): void {
  if (data.length === 0) {
    const csv = "No data available";
    downloadFile(csv, filename, "text/csv");
    return;
  }

  const headers = Object.keys(data[0]);
  const csvRows = [
    headers.join(","),
    ...data.map(row => 
      headers.map(header => {
        const value = row[header];
        const cell = typeof value === "object" ? JSON.stringify(value) : String(value ?? "");
        return cell.includes(",") ? `"${cell.replace(/"/g, '""')}"` : cell;
      }).join(",")
    )
  ];

  const csv = csvRows.join("\n");
  downloadFile(csv, filename, "text/csv");
}

export function generatePDFReport(data: any): void {
  const content = `
<!DOCTYPE html>
<html>
<head>
  <title>Megan_D Security Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
    h1 { color: #0891b2; border-bottom: 2px solid #0891b2; padding-bottom: 10px; }
    .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin: 20px 0; }
    .stat { background: #f1f5f9; padding: 15px; border-radius: 8px; text-align: center; }
    .stat-value { font-size: 24px; font-weight: bold; color: #0891b2; }
    .stat-label { font-size: 12px; color: #64748b; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
    th { background: #f1f5f9; }
    .critical { color: #dc2626; }
    .high { color: #ea580c; }
    .medium { color: #d97706; }
    .low { color: #65a30d; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; }
  </style>
</head>
<body>
  <h1>Megan_D Security Report</h1>
  <p>Generated: ${new Date().toLocaleString()}</p>
  
  <div class="summary">
    <div class="stat">
      <div class="stat-value">${data.summary?.totalScans || 0}</div>
      <div class="stat-label">Total Scans</div>
    </div>
    <div class="stat">
      <div class="stat-value">${data.summary?.totalVulnerabilities || 0}</div>
      <div class="stat-label">Vulnerabilities</div>
    </div>
    <div class="stat">
      <div class="stat-value critical">${data.summary?.criticalCount || 0}</div>
      <div class="stat-label">Critical</div>
    </div>
    <div class="stat">
      <div class="stat-value high">${data.summary?.highCount || 0}</div>
      <div class="stat-label">High</div>
    </div>
  </div>

  <h2>Scan Results</h2>
  <table>
    <thead>
      <tr>
        <th>Target</th>
        <th>Type</th>
        <th>Status</th>
        <th>Timestamp</th>
      </tr>
    </thead>
    <tbody>
      ${(data.scanResults || []).slice(0, 20).map((r: any) => `
        <tr>
          <td>${r.target || "N/A"}</td>
          <td>${r.type || "N/A"}</td>
          <td>${r.vulnerabilities?.length > 0 ? "Issues Found" : "Clean"}</td>
          <td>${r.timestamp ? new Date(r.timestamp).toLocaleString() : "N/A"}</td>
        </tr>
      `).join("")}
    </tbody>
  </table>

  <div class="footer">
    <p>This report was generated by Megan_D Security Operations Platform.</p>
    <p>Report ID: RPT-${Date.now().toString(36).toUpperCase()}</p>
  </div>
</body>
</html>
  `;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.print();
  }
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}