import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync, readdirSync } from 'fs'
import { join } from 'path'
import * as fc from 'fast-check'

// Feature: desktop-mobile-packaging, Property 3: WebView asset resolution
// Validates: Requirements 5.4

const ANDROID_PUBLIC = join(__dirname, '../../android/app/src/main/assets/public')
const INDEX_HTML = join(ANDROID_PUBLIC, 'index.html')

function listFilesInDir(dir: string): Set<string> {
  const result = new Set<string>()
  function recurse(current: string) {
    const entries = readdirSync(current, { withFileTypes: true })
    for (const entry of entries) {
      const full = join(current, entry.name)
      if (entry.isDirectory()) {
        recurse(full)
      } else {
        // Store relative path from ANDROID_PUBLIC
        result.add(full.replace(ANDROID_PUBLIC + '/', '').replace(ANDROID_PUBLIC + '\\', ''))
      }
    }
  }
  recurse(dir)
  return result
}

describe('Capacitor sync — WebView asset resolution (Property 3)', () => {
  it('all asset paths in android index.html resolve to existing files', () => {
    if (!existsSync(INDEX_HTML)) {
      // android/ is generated by npx cap add android + cap sync; skip if not present
      console.warn('Skipping Property 3: android/app/src/main/assets/public/index.html not found (run cap sync first)')
      return
    }

    const html = readFileSync(INDEX_HTML, 'utf-8')
    const presentFiles = listFilesInDir(ANDROID_PUBLIC)

    const srcMatches = Array.from(html.matchAll(/\bsrc=["']([^"']+)["']/g)).map((m) => m[1])
    const hrefMatches = Array.from(html.matchAll(/\bhref=["']([^"']+)["']/g)).map((m) => m[1])
    const allPaths = [...srcMatches, ...hrefMatches]

    const bundledAssets = allPaths.filter(
      (p) => !p.startsWith('http') && !p.startsWith('data:') && p.length > 0
    )

    // Use fast-check to vary the set of asset files and confirm property holds
    // Feature: desktop-mobile-packaging, Property 3: WebView asset resolution
    fc.assert(
      fc.property(
        fc.subarray(bundledAssets, { minLength: 0, maxLength: bundledAssets.length }),
        (subset) => {
          for (const assetPath of subset) {
            const normalized = assetPath.replace(/^\.?\//, '')
            const exists = existsSync(join(ANDROID_PUBLIC, normalized))
            if (!exists) {
              return false
            }
          }
          return true
        }
      ),
      { numRuns: 100 }
    )
  })
})
